In [66]:
from faker import Faker
from faker.providers import BaseProvider
from faker.providers import DynamicProvider
import pandas as pd
import random

# Student

In [67]:
# costumize provider
email_domain = DynamicProvider(provider_name='email_domain',
                               elements = ['gmail', 'yahoo', 'example', 'university', 'hotmail', 'mail'])

email_tl_domain = DynamicProvider(provider_name='email_ext',
                                  elements=['com', 'edu', 'org', 'online'])
# initiate faker instance
fake = Faker()
# add provider to faker 
fake.add_provider(email_domain)
fake.add_provider(email_tl_domain)

In [68]:
data_list = []
for i in range(10):
    f_name = fake.first_name()
    l_name = fake.last_name()
    u_name = (f_name + l_name).lower() + str(random.randrange(0, 9))
    birtday = fake.date_between(start_date='-40y', end_date='-15y')
    data_dict = {
        'account_number': 'AC' + f_name[0] + l_name[0] + birtday.strftime('%m%d%y'),
        'name': f_name,
        'last_name': l_name,
        'birthday': birtday,  
        'email': u_name + '@' + fake.email_domain() + '.' + fake.email_ext(),
        'user_name': u_name,
        'start_date': fake.date_between(start_date='-5y', end_date='-1y'),
        'photo':  u_name + '_pic.jpg',
    } 
    data_list.append(data_dict)

data_profile = pd.DataFrame(data_list)
data_profile.to_csv('Data/Students.csv', index=False)

In [69]:
data_profile.head()

,account_number,name,last_name,birthday,email,user_name,start_date,photo
0,ACJH072590,Jessica,Howard,1990-07-25,jessicahoward2@example.online,jessicahoward2,2020-07-01,jessicahoward2_pic.jpg
1,ACSJ080798,Samantha,Johnson,1998-08-07,samanthajohnson3@hotmail.org,samanthajohnson3,2022-07-17,samanthajohnson3_pic.jpg
2,ACKM111190,Kayla,Mcgrath,1990-11-11,kaylamcgrath0@hotmail.edu,kaylamcgrath0,2023-04-16,kaylamcgrath0_pic.jpg
3,ACRW070287,Robert,White,1987-07-02,robertwhite4@gmail.org,robertwhite4,2021-10-20,robertwhite4_pic.jpg
4,ACET050697,Emily,Turner,1997-05-06,emilyturner4@mail.org,emilyturner4,2020-07-16,emilyturner4_pic.jpg

# Teachers

In [70]:
data_teacher_list = []
for i in range(6):
    f_name = fake.first_name()
    l_name = fake.last_name()
    u_name = (f_name + l_name).lower() + str(random.randrange(0, 9))
    birtday = fake.date_between(start_date='-40y', end_date='-15y')
    data_dict = {
        'account_number': 'TA' + f_name[0] + l_name[0] + birtday.strftime('%m%d%y'),
        'name': f_name,
        'last_name': l_name,
        'birthday': birtday,
        'email': u_name + '@' + fake.email_domain() + '.' + fake.email_ext(),
        'user_name': u_name,
        'start_date': fake.date_between(start_date='-5y', end_date='-1y'),
        'photo': u_name + '_pic.jpg',
    } 
    data_teacher_list.append(data_dict)

data_teacher_profile = pd.DataFrame(data_teacher_list)
data_teacher_profile.to_csv('Data/Teachers.csv', index=False)

In [71]:
data_teacher_profile.head()

,account_number,name,last_name,birthday,email,user_name,start_date,photo
0,TACS082705,Christine,Sharp,2005-08-27,christinesharp3@example.online,christinesharp3,2022-11-22,christinesharp3_pic.jpg
1,TAMP121801,Michael,Price,2001-12-18,michaelprice2@example.org,michaelprice2,2022-09-30,michaelprice2_pic.jpg
2,TAMT010700,Mary,Taylor,2000-01-07,marytaylor2@gmail.edu,marytaylor2,2022-06-07,marytaylor2_pic.jpg
3,TASY062705,Scott,Young,2005-06-27,scottyoung5@yahoo.online,scottyoung5,2020-11-28,scottyoung5_pic.jpg
4,TATR101693,Tammy,Richards,1993-10-16,tammyrichards0@mail.com,tammyrichards0,2019-08-09,tammyrichards0_pic.jpg

# Courses

In [72]:
# create provider for techers choice
teachers_list = list(data_teacher_profile['account_number'])
teacher_acc = DynamicProvider(provider_name='teacher_acc',
                                  elements=teachers_list)
# initiate faker instance
fake = Faker()
# add provider to faker 
fake.add_provider(teacher_acc)

c_names = {
    'computer science': ['python', 'javascript', 'web development'],
    'english language': ['writting', 'english', 'essay writting'],
    'business management': ['business analytics', 'statistics'],
}
courses = {}
codes = []
names = []
category = []
teachers = []
created_dates = []
updated_dates = []
descriptions = []
imgs = []
# Create table for courses
for i, key in enumerate(c_names.keys()):
    for j, name in enumerate(c_names[key]):
        for k, val in enumerate(['introduction to ', 'intermediate ', 'advance ']):
            codes.append(key.split(' ')[0][0] + key.split(' ')[1][0] + str (i + 1) + '0' + str(j) + str(k + 1))
            names.append(val + name)
            category.append(key)
            teachers.append(fake.teacher_acc())
            startdate = fake.date_between(start_date='-8y', end_date='-1y')
            created_dates.append(startdate)
            updated_dates.append(fake.date_between(startdate, 'today'))
            descriptions.append('This course is for ' + val + name + ' in ' + key)
            imgs.append(name + str(k) + '_img.jpg')
# add lists to dictionary
courses['code'] = codes            
courses['name'] = names
courses['category'] = category
courses['teacher'] = teachers
courses['date_created'] = created_dates
courses['date_updated'] = updated_dates
courses['description'] = descriptions
courses['image'] = imgs
courses_df = pd.DataFrame(courses) 
courses_df.to_csv('Data/Courses.csv', index=False)
print(len(courses_df))
courses_df.head()

24

,code,name,category,teacher,date_created,date_updated,description,image
0,cs1001,introduction to python,computer science,TAMP121801,2019-03-27,2021-04-20,This course is for introduction to python in c...,python0_img.jpg
1,cs1002,intermediate python,computer science,TASY062705,2017-06-03,2023-11-09,This course is for intermediate python in comp...,python1_img.jpg
2,cs1003,advance python,computer science,TASY062705,2022-07-26,2022-08-11,This course is for advance python in computer ...,python2_img.jpg
3,cs1011,introduction to javascript,computer science,TALR123193,2017-05-17,2022-03-14,This course is for introduction to javascript ...,javascript0_img.jpg
4,cs1012,intermediate javascript,computer science,TAMT010700,2023-05-06,2024-08-08,This course is for intermediate javascript in ...,javascript1_img.jpg

## Courses' images

In [73]:
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont 

hues = ['blue', 'green', 'orange']

for i, cat in enumerate(courses_df['category']):
    pos = (40, 40)
    
    if cat == 'computer science':
        col = fake.color(hue=hues[0], color_format='rgb', luminosity='light')
    if cat == 'english language':
        col = fake.color(hue=hues[1], color_format='rgb', luminosity='light')
    if cat == 'business management':
        col = fake.color(hue=hues[2], color_format='rgb', luminosity='light')
        pos = (30, 40)
        
    text = courses_df['name'][i].replace(' ', '\n')
    font1 = ImageFont.truetype("Oswald-VariableFont_wght.ttf", 15)
    font2 = ImageFont.truetype("Oswald-VariableFont_wght.ttf", 20)

    img = Image.new(mode="RGB", size=(200, 200), color=col)
    imgDraw = ImageDraw.Draw(img)
    # Add text
    imgDraw.multiline_text(pos, courses_df['category'][i].title(), fill=(250, 250, 250), align="center", font=font2)
    imgDraw.multiline_text((50, 80), text.title(), fill=(0, 0, 0), align="center", font=font2)
    # img.show()
    img.save("Data/courses_images/" + courses_df['image'][i])

# Resources

In [74]:
resources_dict = {}
resourcesTypes_dict = {}
couseIDs = []
codes = []
times = []
resourceTypes = []
contents = []
texts = []
for i, cde in enumerate(courses_df['code']):
    # create providers for faker
    dts = [courses_df['date_created'][i], courses_df['date_updated'][i]]
    date_created = DynamicProvider(provider_name='date_created', elements=dts)
    r_type = DynamicProvider(provider_name='resource_type', elements=['text', 'image', 'video'])
    imgs = DynamicProvider(provider_name='img_type', elements=['png', 'jpg']) 
    # add provider to model
    fake.add_provider(date_created)
    fake.add_provider(r_type)
    fake.add_provider(imgs)
    
    #iterate over the number of courses to create each reosurce
    for j in range(random.randrange(0, 3)):
        couseIDs.append(cde)
        
        codes.append(cde + '.' + str(float(j) + 1))
        # Create the time stamp
        if j == 0:
            times.append(courses_df['date_created'][i])
        else:
            times.append(fake.date_created())
        # resource type
        rtype = fake.resource_type()
        resourceTypes.append(rtype)
        # create resource name
        texts.append(fake.text())
        if rtype == 'image':
            contents.append(fake.file_name(category=rtype, extension='jpg'))
        elif rtype == 'text':
            contents.append(fake.file_name(category=rtype, extension='txt'))
        else:
            contents.append(fake.file_name(category=rtype, extension='mp4'))

resources_dict['code'] = codes
resources_dict['couse_ID'] = couseIDs
resources_dict['timestamp'] = times
resources_dict['content'] = contents
resources_dict['text'] = texts 
resources_df = pd.DataFrame(resources_dict) 
resources_df.to_csv('Data/Resources.csv', index=False)

# ResourcesTypes table
resourcesTypes_dict['couse_ID'] = couseIDs
resourcesTypes_dict['resource_type'] = resourceTypes
resourcesTypes_df = pd.DataFrame(resourcesTypes_dict) 
resourcesTypes_df.to_csv('Data/ResourcesTypes.csv', index=False)

In [75]:
resources_df.head()

,code,couse_ID,timestamp,content,text
0,cs1001.1.0,cs1001,2019-03-27,father.jpg,Gas beyond myself necessary I record. Toward s...
1,cs1002.1.0,cs1002,2017-06-03,investment.txt,Old voice cover senior none away cut. Stop tha...
2,cs1012.1.0,cs1012,2023-05-06,paper.jpg,Night trouble say or. They experience partner ...
3,cs1013.1.0,cs1013,2017-12-06,collection.mp4,Born all young act produce market response. Pa...
4,cs1021.1.0,cs1021,2022-08-23,be.txt,Education agree likely director where cut floo...

In [84]:
print(len(resourcesTypes_df))
resourcesTypes_df.head()

22

  couse_ID resource_type
0   cs1001         image
1   cs1002          text
2   cs1012         image
3   cs1013         video
4   cs1021          text

In [96]:
import cv2
import glob
path = resources_df['content']
for i, cat in enumerate(resourcesTypes_df['resource_type']):
    c_path = "Data/resources_files/" + path[i]

    if cat == 'text':
        # Open the file 
        with open(c_path, 'w') as file:
            # Add content
            file.write("Text file sample")
    if cat == 'image':
        img = Image.new(mode="RGB", size=(200, 200), color=fake.color(hue='blue'))
        imgDraw = ImageDraw.Draw(img)
        img.save(c_path)
    
    if cat == 'video':
        # Initialize video writer
        video = cv2.VideoWriter(c_path, cv2.VideoWriter_fourcc(*'mp4v'), 24, (200, 200))

        # Read images and write them to the video
        for file in sorted(glob.glob('images/*.jpg')):
            img = cv2.imread(file)
            # attaches images to video
            video.write(img)
        video.release()

# Enrollment

In [97]:
# create provider for course choice
course_list = list(courses_df['code'])
course_code = DynamicProvider(provider_name='course_code',
                                  elements=course_list)
# initiate faker instance
fake = Faker()
# add provider to faker 
fake.add_provider(course_code)

students = data_profile['account_number']
starts = data_profile['start_date']

enrollments = {}
timeStamps = []
courses_l =[]
# create a table with enrollment timestamp, student and course
for i, student in enumerate(students):
    timeStamps.append(fake.date_between(starts[i], 'today'))
    courses_l.append(fake.course_code())
enrollments['date'] = timeStamps
enrollments['student'] = students
enrollments['course'] = courses_l
enrollments_df = pd.DataFrame(enrollments)

enrollments_df.to_csv('Data/Enrollments.csv', index=False)    
enrollments_df

         date     student  course
0  2024-05-06  ACJH072590  cs1002
1  2024-01-19  ACSJ080798  bm3012
2  2024-03-13  ACKM111190  bm3001
3  2022-01-23  ACRW070287  el2021
4  2024-03-20  ACET050697  cs1011
5  2023-12-25  ACJJ060908  bm3001
6  2021-01-14  ACBR061694  el2012
7  2021-11-27  ACTB043002  cs1021
8  2023-09-17  ACDW052885  cs1023
9  2023-04-29  ACAM071402  el2003